language: php

php:
  - 7.0

before_install:
  - nvm install node
  - nvm use node

install:
  - composer install --no-dev --no-interaction
  - npm install

script: npm run production

after_success:
  - rm -rf node_modules/
  - php artisan config:cache
  - php artisan route:cache
  - php artisan optimize

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy
  on:
    branch: master

branches:
  only:
  - master